name: Release

on:
  push:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - run: zig fmt --check src/*.zig
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env
        run: |
          echo "Version=$(cat build.zig.zon | grep -o -E '\b[0-9]+\.[0-9]+\.[0-9]+\b') >> $GITHUB_ENV"
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - run: |
          sudo apt install libgtk-3-0 libgtk-3-dev
          zig build -Doptimize=ReleaseSmall
          tar -czf zigenity.tgz zig-out/bin/zigenity
      - name: Release
        run: hub release create ${{ env.Version }} -m "Automatic release ${{ env.Version }} $(date +'%Y.%m.%d_%H-%M')" -a zigenity.tgz
        #uses: softprops/action-gh-release@v2
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #with:
        #  tag_name: ${{ env.Version }}
        #  generate_release_notes: true
        #  files: |
        #    zig-out/bin/zigenity
